{"nbformat":4,"nbformat_minor":0,"metadata":{"colab":{"name":"SinGAN-tf.ipynb","provenance":[{"file_id":"14mrsA4Bfdw7v_D9_h7aR5ajaFIb_aZxK","timestamp":1629213904684}],"collapsed_sections":[]},"kernelspec":{"name":"python3","display_name":"Python 3"},"language_info":{"name":"python"},"accelerator":"GPU"},"cells":[{"cell_type":"code","metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"FGrUB80Ecc9X","executionInfo":{"status":"ok","timestamp":1629249057039,"user_tz":420,"elapsed":200,"user":{"displayName":"Bashar Naji","photoUrl":"https://lh3.googleusercontent.com/a-/AOh14GiqNb17qzkuI1gQbZbnBrQxHHcq3uPGuTrZtlYYKA=s64","userId":"08294858932832447445"}},"outputId":"7f07462a-fab3-4a95-c711-d097380413ee"},"source":["from google.colab import drive\n","import os\n","drive.mount('/content/drive')\n","os.chdir('/content/drive/MyDrive/FourthBrain/Capstone Samsung OCT/sinGAN-tf')"],"execution_count":11,"outputs":[{"output_type":"stream","text":["Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount(\"/content/drive\", force_remount=True).\n"],"name":"stdout"}]},{"cell_type":"code","metadata":{"id":"LrkbnSOxc7AW","colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"status":"ok","timestamp":1629245143754,"user_tz":420,"elapsed":2245323,"user":{"displayName":"Bashar Naji","photoUrl":"https://lh3.googleusercontent.com/a-/AOh14GiqNb17qzkuI1gQbZbnBrQxHHcq3uPGuTrZtlYYKA=s64","userId":"08294858932832447445"}},"outputId":"a5e67a35-e2a6-49f0-b4d4-773b5e47900c"},"source":["!python main.py train --image images/train/CNV-53018-1.jpeg --num_scales 8"],"execution_count":null,"outputs":[{"output_type":"stream","text":["Directory ./training_checkpoints already exists\n","2021-08-17 23:28:20.874713: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n","2021-08-17 23:28:20.883977: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n","2021-08-17 23:28:20.884993: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n","2021-08-17 23:28:20.886504: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n","2021-08-17 23:28:20.887466: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n","2021-08-17 23:28:20.888364: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n","2021-08-17 23:28:21.504800: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n","2021-08-17 23:28:21.505799: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n","2021-08-17 23:28:21.506744: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n","2021-08-17 23:28:21.507610: W tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:39] Overriding allow_growth setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was 0.\n","2021-08-17 23:28:21.507691: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1510] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 15435 MB memory:  -> device: 0, name: Tesla P100-PCIE-16GB, pci bus id: 0000:00:04.0, compute capability: 6.0\n","(1, 25, 33, 3)\n","(1, 28, 44, 3)\n","(1, 38, 59, 3)\n","(1, 50, 79, 3)\n","(1, 67, 105, 3)\n","(1, 90, 140, 3)\n","(1, 120, 187, 3)\n","(1, 161, 250, 3)\n","0\n","2021-08-17 23:28:22.060501: I tensorflow/stream_executor/cuda/cuda_dnn.cc:369] Loaded cuDNN version 8004\n","2021-08-17 23:28:38.698250: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:185] None of the MLIR Optimization Passes are enabled (registered 2)\n"," dis_loss = -1.370\n"," gen_loss = -0.294\n"," rec_loss = 0.044\n","Time taken for scale 0 is 144.52 sec\n","\n","1\n"," dis_loss = -0.279\n"," gen_loss = -1.526\n"," rec_loss = 0.001\n","Time taken for scale 1 is 165.43 sec\n","\n","2\n"," dis_loss = -0.029\n"," gen_loss = 1.795\n"," rec_loss = 0.000\n","Time taken for scale 2 is 198.87 sec\n","\n","3\n"," dis_loss = -0.018\n"," gen_loss = 2.632\n"," rec_loss = 0.000\n","Time taken for scale 3 is 224.55 sec\n","\n","4\n"," dis_loss = 0.017\n"," gen_loss = -0.102\n"," rec_loss = 0.001\n","Time taken for scale 4 is 242.67 sec\n","\n","5\n"," dis_loss = 0.028\n"," gen_loss = 0.197\n"," rec_loss = 0.001\n","Time taken for scale 5 is 280.00 sec\n","\n","6\n"," dis_loss = 0.008\n"," gen_loss = 0.024\n"," rec_loss = 0.001\n","Time taken for scale 6 is 390.12 sec\n","\n","7\n"," dis_loss = 0.007\n"," gen_loss = 0.415\n"," rec_loss = 0.001\n","Time taken for scale 7 is 594.15 sec\n","\n"],"name":"stdout"}]},{"cell_type":"markdown","metadata":{"id":"TWP4GNyIBamk"},"source":["dir_path = \"./images/batch/\"\n","\n","for f in os.listdir(dir_path):\n","  file_path = dir_path + f\n","  print (file_path)\n","  !python main.py inference --image file_path  --dir ./training_checkpoints  --mode random_sample  --inject_scale 0"]},{"cell_type":"code","metadata":{"id":"BnNBfV8id1ta","colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"status":"ok","timestamp":1629250396298,"user_tz":420,"elapsed":9700,"user":{"displayName":"Bashar Naji","photoUrl":"https://lh3.googleusercontent.com/a-/AOh14GiqNb17qzkuI1gQbZbnBrQxHHcq3uPGuTrZtlYYKA=s64","userId":"08294858932832447445"}},"outputId":"eb30bf05-3e28-4f4c-8e4b-87e0e416da1b"},"source":["!python main.py inference --image ./images/batch/CNV-6668596-1.jpeg  --dir ./training_checkpoints  --mode random_sample  --inject_scale 0"],"execution_count":18,"outputs":[{"output_type":"stream","text":["2021-08-18 01:33:09.008548: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n","2021-08-18 01:33:09.017429: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n","2021-08-18 01:33:09.018432: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n","2021-08-18 01:33:09.019730: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n","2021-08-18 01:33:09.020653: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n","2021-08-18 01:33:09.021620: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n","2021-08-18 01:33:09.639358: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n","2021-08-18 01:33:09.640324: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n","2021-08-18 01:33:09.641199: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n","2021-08-18 01:33:09.642024: W tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:39] Overriding allow_growth setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was 0.\n","2021-08-18 01:33:09.642094: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1510] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 15435 MB memory:  -> device: 0, name: Tesla P100-PCIE-16GB, pci bus id: 0000:00:04.0, compute capability: 6.0\n","(1, 21, 33, 3)\n","(1, 28, 44, 3)\n","(1, 38, 59, 3)\n","(1, 50, 79, 3)\n","(1, 67, 105, 3)\n","(1, 90, 140, 3)\n","(1, 120, 187, 3)\n","(1, 161, 250, 3)\n","Directory ./results/random_sample createrd\n","2021-08-18 01:33:12.219419: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:185] None of the MLIR Optimization Passes are enabled (registered 2)\n","2021-08-18 01:33:12.823066: I tensorflow/stream_executor/cuda/cuda_dnn.cc:369] Loaded cuDNN version 8004\n"],"name":"stdout"}]},{"cell_type":"code","metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"oJPveAc8p2_j","executionInfo":{"status":"ok","timestamp":1629250072586,"user_tz":420,"elapsed":2896,"user":{"displayName":"Bashar Naji","photoUrl":"https://lh3.googleusercontent.com/a-/AOh14GiqNb17qzkuI1gQbZbnBrQxHHcq3uPGuTrZtlYYKA=s64","userId":"08294858932832447445"}},"outputId":"391a7038-5f34-43ed-9b94-c5ec81c68580"},"source":["!python main.py inference --image NORMAL-220042-1.jpeg  --dir ./training_checkpoints  --mode random_sample  --inject_scale 0 --num_samples 1"],"execution_count":14,"outputs":[{"output_type":"stream","text":["Traceback (most recent call last):\n","  File \"main.py\", line 97, in <module>\n","    main()\n","  File \"main.py\", line 68, in main\n","    assert os.path.exists(args.image), 'Reference image not found !'\n","AssertionError: Reference image not found !\n"],"name":"stdout"}]},{"cell_type":"code","metadata":{"id":"xBLPIJAhrQfP"},"source":[""],"execution_count":null,"outputs":[]}]}